Feature: Fixed OrderInfo part
block-crafters/cryptofeed pull request #69
Opened 2022-08-12 06:06 UTC by MinsungKim-BlockCrafters

## What does this PR do?

## Changes

Fixed `OrderInfo`'s fixed timestamp key

## References

2022-08-12 06:32 UTC, boseok-bc approved these changes

2022-08-12 06:32 UTC, boseok-bc commented on cryptofeed/backends/redis.py
> +        timestamp_key = (self.forced_timestamp_key or key or self.key) + ":" + type(self).timestamp_key_suffix
이렇게 쓰면 `OrderInfoLatestRedis` 처럼 `self.forced_timestamp_key` 를 attribute로 설정한 instance 에서는 instance variable로 쓰고 다른 instance 에서는 class variable 인 `forced_timestamp_key` 를 가져다 쓰는거죠? 동작은 의도한 동작대로 할텐데 좋은 practice 인지는 확신이 없네요. 관련해서 레퍼런스 주실것 있으면 같이 보면 좋을것 같아요 ㅎㅎ

2022-08-12 07:33 UTC, MinsungKim-BlockCrafters commented on cryptofeed/backends/redis.py
> +        timestamp_key = (self.forced_timestamp_key or key or self.key) + ":" + type(self).timestamp_key_suffix
https://howchoo.com/python/understanding-class-vs-instance-variables-in-python-3

좋은 practice는 아니라고 하는 군요..

2022-08-12 07:36 UTC, boseok-bc requested changes

2022-08-12 07:36 UTC, boseok-bc commented on cryptofeed/backends/redis.py
> +        self.forced_timestamp_key = f"order_info:{goni_exchange_id}:{goni_account_id}:{goni_cryptofeed_symbol}"
제가 이부분을 이전리뷰에서 못봤네요 cryptofeed는 goni 의 존재를 몰라야합니다!! cryptofeed 가 모델에 dependency가 있어서는 안돼요.
`__init__`  함수를 통해서 goni oriented 된 parameter로 받지 마시고
`write` 함수를 통해 넘어오는 값들로 `writer` 함수에서 timestamp key를 만들어 쓰는 식으로 변경해주세요!
ref)
https://github.com/block-crafters/cryptofeed/pull/69/files#diff-1292aadfd734dec7a2ec65b3f23b872a13bf478088ec51accffc541450362fa7R339
https://github.com/block-crafters/cryptofeed/pull/69/files#diff-1292aadfd734dec7a2ec65b3f23b872a13bf478088ec51accffc541450362fa7L335

2022-08-12 07:55 UTC, MinsungKim-BlockCrafters commented on cryptofeed/backends/redis.py
> +        self.forced_timestamp_key = f"order_info:{goni_exchange_id}:{goni_account_id}:{goni_cryptofeed_symbol}"
account id, exchange id, cryptofeed symbol은 어차피 다른 모델에서도 사용할 수 있는 파라미터니까 파라미터 네이밍만 바꿔주면 간단하게 해결될 것 같은데.. 그렇지 않나요?

현재 구조가 `forced_timestamp_key or key or self.key` 로 되어 있기 때문에 해당 방식으로 구조를 구현하는 것이 바로 생각나진 않네요.

2022-08-12 08:14 UTC, boseok-bc commented on cryptofeed/backends/redis.py
> +        self.forced_timestamp_key = f"order_info:{goni_exchange_id}:{goni_account_id}:{goni_cryptofeed_symbol}"
네이밍 변경으로 goni dependency를 없앨 수 있겠지만 같은 정보에 대해서 다른 source로 부터 불필요하게 두번 값을 넣으면 안될것 같아요 ㅎㅎ

`RedisCallback` 부모 class에 timestamp key 를 구성하는 함수 (가칭) `get_timestamp_key` default 함수를 만들고 `OrderInfoLatestRedis` 에서 override 해서 쓰면 되지 않을까요?

2022-08-16 23:55 UTC, boseok-bc commented on cryptofeed/feed.py
> +                    )
`type(self).__name__.upper()` 대신에 `self.id` 로 쓸 수 있습니다.
https://github.com/block-crafters/cryptofeed/blob/bc-master/cryptofeed/exchanges/bitmex.py#L30

2022-08-16 23:55 UTC, boseok-bc commented on cryptofeed/feed.py
> +                    )
`origin_symbols[0]` 형태로 하게되면 `symbols` 가 복수의 symbol 일때 맨처음 것으로 하드코딩 될것 같은데... 그렇지 않나요? ([ETH-USD-PERP, BTC-USD-PERP] 일때 채널은 2개가 각각 생성되어도 timestamp는 항상 ETH-USD-PERP 로 박힐것으로 코드가 읽히네요)

각 symbol 까지 여기서 forced_timestamp_key에 포함시키기 어렵다면, symbol은 writer 파트에서 처리하면 어떨까요?
모든 `await self.queue.put` 함수를 보시면 항상 `feed`, `symbol` 을 포함하고 있기 때문에 해당 정보를 이용해서 원하는 key를 구성할 수 있을거 같아서요 
https://github.com/block-crafters/cryptofeed/blob/bc-master/cryptofeed/backends/redis.py#L61

만약에 이렇게가 어렵다면, 현재코드에서 일단은 symbol 을 제외한 것을 forced_timestamp_key 로 쓰는 정도로 마무리 합시다

2022-08-17 06:28 UTC, boseok-bc approved these changes
수고하셨습니다!

2022-08-17 07:51 UTC, merged